[tool.mypy]
ignore_missing_imports = true
cache_dir = "./.devenv/state/mypy_cache"

[tool.pylint.messages_control]
disable = [
    "missing-module-docstring",
    "missing-class-docstring", 
    "missing-function-docstring",
    "too-few-public-methods",
    "too-many-arguments",
    "too-many-positional-arguments",
    "fixme",
    "broad-exception-caught"
]

[tool.pylint.format]
max-line-length = 120

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 120

[tool.black]
line-length = 120
